#!/bin/sh

REPORT_CONFIG="/etc/clearos/proxy_report.conf"
DBINFO="/var/clearos/system_database/reports"
MYSQL="/usr/clearos/sandbox/usr/bin/mysql"

# Check database status
#----------------------

[ -e /var/lib/system-mysql/mysql.sock ] || exit 0

# Grab the number of records to keep
#-----------------------------------

RECORDS=`grep ^records $REPORT_CONFIG 2>/dev/null | sed 's/.*=//'`
if [ -z "$RECORDS" ]; then
	RECORDS=2000000
fi

# Grab database password
#-----------------------

DBPASS=`grep ^password $DBINFO 2>/dev/null | sed "s/^password[[:space:]]*=[[:space:]]*//"`

if [ -z "$DBPASS" ]; then
    echo "Unable to authenticate with database"
    exit 1
fi

# Purge database
#---------------

$MYSQL -ureports -p"$DBPASS" -e "\
DROP TABLE IF EXISTS proxy_prune; \
CREATE TABLE proxy_prune SELECT * FROM proxy ORDER BY timestamp DESC LIMIT $RECORDS; \
RENAME TABLE proxy TO proxy_old, proxy_prune TO proxy;  \
DROP TABLE proxy_old; \
" reports
